#install.packages("rJava", repos = "https://cran.r-project.org")
library("rJava")
.jinit()
.jaddClassPath("./")
HelloWorld <- J("com/satyajit/demo/HelloWorld")
hello <- .jnew(HelloWorld)
arr <- .jarray(as.integer(c(3, 5, 2, 1, 6)))
.jcall(hello, "V", "print", arr)